# Generated by Django 3.2 on 2021-04-11 15:02

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=accounts.utils.get_user_upload_image_path),
        ),
    ]
