# Generated by Django 3.2 on 2021-04-16 15:32

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discriptoin', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts.utils.get_post_upload_image_path)),
                ('name', models.TextField(max_length=65)),
                ('price', models.IntegerField(max_length=50)),
            ],
        ),
    ]
