# Generated by Django 3.2 on 2021-04-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discriptoin',
            new_name='description',
        ),
    ]
