# Generated by Django 3.2 on 2021-04-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_category'),
        ('posts', '0007_post_tags'),
    ]

    operations = [
    ]
